trigger:
- main
- develop

pr:
  branches:
    include:
    - main
    - develop

pool:
  vmImage: ubuntu-latest

steps:
- task: DotNetCoreCLI@2
  displayName: 'dotnet build aspdotnet-site'
  inputs:
    command: 'build'
    projects: '**/*.csproj'